// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaceQBOLkzd-O3Ffi7_Pkbl8rRkPfksVw',
    appId: '1:411541045729:web:fb17f21526f1f75faf52a0',
    messagingSenderId: '411541045729',
    projectId: 'whispulse-90474',
    authDomain: 'whispulse-90474.firebaseapp.com',
    storageBucket: 'whispulse-90474.firebasestorage.app',
    measurementId: 'G-SX74T874LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB3qmiU3q_OMVzJUaUBuCfizmkdvRNVdM',
    appId: '1:411541045729:android:d8efa390620cc8b6af52a0',
    messagingSenderId: '411541045729',
    projectId: 'whispulse-90474',
    storageBucket: 'whispulse-90474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN0eSQLWQuaLL2ezRbGEOv4E6hs7f971w',
    appId: '1:411541045729:ios:1ea96a850e0e7ea9af52a0',
    messagingSenderId: '411541045729',
    projectId: 'whispulse-90474',
    storageBucket: 'whispulse-90474.firebasestorage.app',
    iosBundleId: 'com.example.getnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN0eSQLWQuaLL2ezRbGEOv4E6hs7f971w',
    appId: '1:411541045729:ios:1ea96a850e0e7ea9af52a0',
    messagingSenderId: '411541045729',
    projectId: 'whispulse-90474',
    storageBucket: 'whispulse-90474.firebasestorage.app',
    iosBundleId: 'com.example.getnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaceQBOLkzd-O3Ffi7_Pkbl8rRkPfksVw',
    appId: '1:411541045729:web:57d79b1079cb645caf52a0',
    messagingSenderId: '411541045729',
    projectId: 'whispulse-90474',
    authDomain: 'whispulse-90474.firebaseapp.com',
    storageBucket: 'whispulse-90474.firebasestorage.app',
    measurementId: 'G-X5W5FHVC9M',
  );
}
